### ISSUE TITLE
Not compatible with Node 9.x

### ISSUE THREAD

**Issue by ceremcem** [Cloud-Automation/node-net-reconnect#4]
`node-net-reconnect` fails to install if node version is > 8.x

**Comment by CaptainChemist** [comment]
I ran into this too- did you ever figure out a solution for it or did you just use an older version of node?

**Comment by ceremcem** [comment]
Yes, I was using Node v8.x for that reason. However, It seems to install successfully in Node 10.x. (Thanks for reminding this issue, I was wonderin why I restricted node v8 in [this README](https://github.com/aktos-io/scadajs-template/blame/339c1446de5539a61ac261ffb25dda7d6c116108/install.md#L3))

**Comment by stefanpoeter** [comment]
Hey @ceremcem Since this modules uses standard NodeJs API this should work fine on most and newer versions. Just remember that odd version numbers are non LTS Versions. So make sure you always stick to even node.js version numbers.
